// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: serviciosservidor.proto

package serviciosservidor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciosservidor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosservidor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_serviciosservidor_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CodSeguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodigoSeguimiento int32 `protobuf:"varint,1,opt,name=CodigoSeguimiento,proto3" json:"CodigoSeguimiento,omitempty"`
}

func (x *CodSeguimiento) Reset() {
	*x = CodSeguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciosservidor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodSeguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodSeguimiento) ProtoMessage() {}

func (x *CodSeguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosservidor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodSeguimiento.ProtoReflect.Descriptor instead.
func (*CodSeguimiento) Descriptor() ([]byte, []int) {
	return file_serviciosservidor_proto_rawDescGZIP(), []int{1}
}

func (x *CodSeguimiento) GetCodigoSeguimiento() int32 {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciosservidor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosservidor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_serviciosservidor_proto_rawDescGZIP(), []int{2}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Orden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo    string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre  string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor   int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen  string `protobuf:"bytes,5,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Orden) Reset() {
	*x = Orden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciosservidor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orden) ProtoMessage() {}

func (x *Orden) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosservidor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orden.ProtoReflect.Descriptor instead.
func (*Orden) Descriptor() ([]byte, []int) {
	return file_serviciosservidor_proto_rawDescGZIP(), []int{3}
}

func (x *Orden) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Orden) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Orden) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Orden) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Orden) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Orden) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type Paquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CodigoSeguimiento int32  `protobuf:"varint,2,opt,name=CodigoSeguimiento,proto3" json:"CodigoSeguimiento,omitempty"`
	Tipo              string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor             int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Intentos          int32  `protobuf:"varint,5,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado            string `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Paquete) Reset() {
	*x = Paquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciosservidor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paquete) ProtoMessage() {}

func (x *Paquete) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosservidor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paquete.ProtoReflect.Descriptor instead.
func (*Paquete) Descriptor() ([]byte, []int) {
	return file_serviciosservidor_proto_rawDescGZIP(), []int{4}
}

func (x *Paquete) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Paquete) GetCodigoSeguimiento() int32 {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return 0
}

func (x *Paquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Paquete) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Paquete) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *Paquete) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type InformacionPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodigoSeguimiento int32  `protobuf:"varint,1,opt,name=CodigoSeguimiento,proto3" json:"CodigoSeguimiento,omitempty"`
	Estado            string `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *InformacionPaquete) Reset() {
	*x = InformacionPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciosservidor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformacionPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformacionPaquete) ProtoMessage() {}

func (x *InformacionPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosservidor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformacionPaquete.ProtoReflect.Descriptor instead.
func (*InformacionPaquete) Descriptor() ([]byte, []int) {
	return file_serviciosservidor_proto_rawDescGZIP(), []int{5}
}

func (x *InformacionPaquete) GetCodigoSeguimiento() int32 {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return 0
}

func (x *InformacionPaquete) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_serviciosservidor_proto protoreflect.FileDescriptor

var file_serviciosservidor_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x64, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x22, 0x1d, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3e, 0x0a, 0x0e, 0x43,
	0x6f, 0x64, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x2c, 0x0a,
	0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f,
	0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x06, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x8b, 0x01,
	0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x07,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67,
	0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x22, 0x5a, 0x0a, 0x12, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x64,
	0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x32,
	0x86, 0x02, 0x0a, 0x0f, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x50, 0x6f,
	0x73, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69,
	0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x1a, 0x1a, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0e, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x12, 0x1a, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x1a,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64,
	0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e, 0x50,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x22, 0x00, 0x32, 0xb6, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x52,
	0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x18, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x6e, 0x1a, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f,
	0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x64, 0x53, 0x65, 0x67,
	0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x13, 0x53, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74,
	0x6f, 0x12, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x64, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69,
	0x65, 0x6e, 0x74, 0x6f, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x67, 0x65, 0x6e,
	0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64,
	0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serviciosservidor_proto_rawDescOnce sync.Once
	file_serviciosservidor_proto_rawDescData = file_serviciosservidor_proto_rawDesc
)

func file_serviciosservidor_proto_rawDescGZIP() []byte {
	file_serviciosservidor_proto_rawDescOnce.Do(func() {
		file_serviciosservidor_proto_rawDescData = protoimpl.X.CompressGZIP(file_serviciosservidor_proto_rawDescData)
	})
	return file_serviciosservidor_proto_rawDescData
}

var file_serviciosservidor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_serviciosservidor_proto_goTypes = []interface{}{
	(*Message)(nil),            // 0: serviciosservidor.Message
	(*CodSeguimiento)(nil),     // 1: serviciosservidor.CodSeguimiento
	(*Estado)(nil),             // 2: serviciosservidor.Estado
	(*Orden)(nil),              // 3: serviciosservidor.Orden
	(*Paquete)(nil),            // 4: serviciosservidor.Paquete
	(*InformacionPaquete)(nil), // 5: serviciosservidor.InformacionPaquete
}
var file_serviciosservidor_proto_depIdxs = []int32{
	5, // 0: serviciosservidor.CamionesService.EntregaPosicion:input_type -> serviciosservidor.InformacionPaquete
	0, // 1: serviciosservidor.CamionesService.InformaEntrega:input_type -> serviciosservidor.Message
	0, // 2: serviciosservidor.CamionesService.RecibeInstrucciones:input_type -> serviciosservidor.Message
	3, // 3: serviciosservidor.ClienteService.RealizaOrden:input_type -> serviciosservidor.Orden
	1, // 4: serviciosservidor.ClienteService.SolicitaSeguimiento:input_type -> serviciosservidor.CodSeguimiento
	0, // 5: serviciosservidor.CamionesService.EntregaPosicion:output_type -> serviciosservidor.Message
	0, // 6: serviciosservidor.CamionesService.InformaEntrega:output_type -> serviciosservidor.Message
	4, // 7: serviciosservidor.CamionesService.RecibeInstrucciones:output_type -> serviciosservidor.Paquete
	1, // 8: serviciosservidor.ClienteService.RealizaOrden:output_type -> serviciosservidor.CodSeguimiento
	2, // 9: serviciosservidor.ClienteService.SolicitaSeguimiento:output_type -> serviciosservidor.Estado
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serviciosservidor_proto_init() }
func file_serviciosservidor_proto_init() {
	if File_serviciosservidor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serviciosservidor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciosservidor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodSeguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciosservidor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciosservidor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciosservidor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciosservidor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformacionPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serviciosservidor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_serviciosservidor_proto_goTypes,
		DependencyIndexes: file_serviciosservidor_proto_depIdxs,
		MessageInfos:      file_serviciosservidor_proto_msgTypes,
	}.Build()
	File_serviciosservidor_proto = out.File
	file_serviciosservidor_proto_rawDesc = nil
	file_serviciosservidor_proto_goTypes = nil
	file_serviciosservidor_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CamionesServiceClient is the client API for CamionesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CamionesServiceClient interface {
	EntregaPosicion(ctx context.Context, in *InformacionPaquete, opts ...grpc.CallOption) (*Message, error)
	InformaEntrega(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	RecibeInstrucciones(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Paquete, error)
}

type camionesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCamionesServiceClient(cc grpc.ClientConnInterface) CamionesServiceClient {
	return &camionesServiceClient{cc}
}

func (c *camionesServiceClient) EntregaPosicion(ctx context.Context, in *InformacionPaquete, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/serviciosservidor.CamionesService/EntregaPosicion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *camionesServiceClient) InformaEntrega(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/serviciosservidor.CamionesService/InformaEntrega", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *camionesServiceClient) RecibeInstrucciones(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Paquete, error) {
	out := new(Paquete)
	err := c.cc.Invoke(ctx, "/serviciosservidor.CamionesService/RecibeInstrucciones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CamionesServiceServer is the server API for CamionesService service.
type CamionesServiceServer interface {
	EntregaPosicion(context.Context, *InformacionPaquete) (*Message, error)
	InformaEntrega(context.Context, *Message) (*Message, error)
	RecibeInstrucciones(context.Context, *Message) (*Paquete, error)
}

// UnimplementedCamionesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCamionesServiceServer struct {
}

func (*UnimplementedCamionesServiceServer) EntregaPosicion(context.Context, *InformacionPaquete) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntregaPosicion not implemented")
}
func (*UnimplementedCamionesServiceServer) InformaEntrega(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformaEntrega not implemented")
}
func (*UnimplementedCamionesServiceServer) RecibeInstrucciones(context.Context, *Message) (*Paquete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecibeInstrucciones not implemented")
}

func RegisterCamionesServiceServer(s *grpc.Server, srv CamionesServiceServer) {
	s.RegisterService(&_CamionesService_serviceDesc, srv)
}

func _CamionesService_EntregaPosicion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformacionPaquete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionesServiceServer).EntregaPosicion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviciosservidor.CamionesService/EntregaPosicion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionesServiceServer).EntregaPosicion(ctx, req.(*InformacionPaquete))
	}
	return interceptor(ctx, in, info, handler)
}

func _CamionesService_InformaEntrega_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionesServiceServer).InformaEntrega(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviciosservidor.CamionesService/InformaEntrega",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionesServiceServer).InformaEntrega(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _CamionesService_RecibeInstrucciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionesServiceServer).RecibeInstrucciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviciosservidor.CamionesService/RecibeInstrucciones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionesServiceServer).RecibeInstrucciones(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _CamionesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serviciosservidor.CamionesService",
	HandlerType: (*CamionesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntregaPosicion",
			Handler:    _CamionesService_EntregaPosicion_Handler,
		},
		{
			MethodName: "InformaEntrega",
			Handler:    _CamionesService_InformaEntrega_Handler,
		},
		{
			MethodName: "RecibeInstrucciones",
			Handler:    _CamionesService_RecibeInstrucciones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviciosservidor.proto",
}

// ClienteServiceClient is the client API for ClienteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClienteServiceClient interface {
	RealizaOrden(ctx context.Context, in *Orden, opts ...grpc.CallOption) (*CodSeguimiento, error)
	SolicitaSeguimiento(ctx context.Context, in *CodSeguimiento, opts ...grpc.CallOption) (*Estado, error)
}

type clienteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClienteServiceClient(cc grpc.ClientConnInterface) ClienteServiceClient {
	return &clienteServiceClient{cc}
}

func (c *clienteServiceClient) RealizaOrden(ctx context.Context, in *Orden, opts ...grpc.CallOption) (*CodSeguimiento, error) {
	out := new(CodSeguimiento)
	err := c.cc.Invoke(ctx, "/serviciosservidor.ClienteService/RealizaOrden", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clienteServiceClient) SolicitaSeguimiento(ctx context.Context, in *CodSeguimiento, opts ...grpc.CallOption) (*Estado, error) {
	out := new(Estado)
	err := c.cc.Invoke(ctx, "/serviciosservidor.ClienteService/SolicitaSeguimiento", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClienteServiceServer is the server API for ClienteService service.
type ClienteServiceServer interface {
	RealizaOrden(context.Context, *Orden) (*CodSeguimiento, error)
	SolicitaSeguimiento(context.Context, *CodSeguimiento) (*Estado, error)
}

// UnimplementedClienteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClienteServiceServer struct {
}

func (*UnimplementedClienteServiceServer) RealizaOrden(context.Context, *Orden) (*CodSeguimiento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RealizaOrden not implemented")
}
func (*UnimplementedClienteServiceServer) SolicitaSeguimiento(context.Context, *CodSeguimiento) (*Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitaSeguimiento not implemented")
}

func RegisterClienteServiceServer(s *grpc.Server, srv ClienteServiceServer) {
	s.RegisterService(&_ClienteService_serviceDesc, srv)
}

func _ClienteService_RealizaOrden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Orden)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClienteServiceServer).RealizaOrden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviciosservidor.ClienteService/RealizaOrden",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClienteServiceServer).RealizaOrden(ctx, req.(*Orden))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClienteService_SolicitaSeguimiento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodSeguimiento)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClienteServiceServer).SolicitaSeguimiento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviciosservidor.ClienteService/SolicitaSeguimiento",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClienteServiceServer).SolicitaSeguimiento(ctx, req.(*CodSeguimiento))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClienteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serviciosservidor.ClienteService",
	HandlerType: (*ClienteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RealizaOrden",
			Handler:    _ClienteService_RealizaOrden_Handler,
		},
		{
			MethodName: "SolicitaSeguimiento",
			Handler:    _ClienteService_SolicitaSeguimiento_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviciosservidor.proto",
}
