// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: serviciomensajeria.proto

package sm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Paquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CodigoSeguimiento int32  `protobuf:"varint,2,opt,name=CodigoSeguimiento,proto3" json:"CodigoSeguimiento,omitempty"`
	Tipo              string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor             int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Intentos          int32  `protobuf:"varint,5,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado            string `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
	Origen            string `protobuf:"bytes,7,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino           string `protobuf:"bytes,8,opt,name=destino,proto3" json:"destino,omitempty"`
	Nombre            string `protobuf:"bytes,9,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *Paquete) Reset() {
	*x = Paquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paquete) ProtoMessage() {}

func (x *Paquete) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paquete.ProtoReflect.Descriptor instead.
func (*Paquete) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{1}
}

func (x *Paquete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Paquete) GetCodigoSeguimiento() int32 {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return 0
}

func (x *Paquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Paquete) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Paquete) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *Paquete) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Paquete) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Paquete) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Paquete) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type InformePaquetes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paquetes []*Paquete `protobuf:"bytes,1,rep,name=paquetes,proto3" json:"paquetes,omitempty"`
}

func (x *InformePaquetes) Reset() {
	*x = InformePaquetes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformePaquetes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformePaquetes) ProtoMessage() {}

func (x *InformePaquetes) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformePaquetes.ProtoReflect.Descriptor instead.
func (*InformePaquetes) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{2}
}

func (x *InformePaquetes) GetPaquetes() []*Paquete {
	if x != nil {
		return x.Paquetes
	}
	return nil
}

type InformacionPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodigoSeguimiento int32  `protobuf:"varint,1,opt,name=CodigoSeguimiento,proto3" json:"CodigoSeguimiento,omitempty"`
	Estado            string `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *InformacionPaquete) Reset() {
	*x = InformacionPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformacionPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformacionPaquete) ProtoMessage() {}

func (x *InformacionPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformacionPaquete.ProtoReflect.Descriptor instead.
func (*InformacionPaquete) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{3}
}

func (x *InformacionPaquete) GetCodigoSeguimiento() int32 {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return 0
}

func (x *InformacionPaquete) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type CodSeguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodigoSeguimiento int32 `protobuf:"varint,1,opt,name=CodigoSeguimiento,proto3" json:"CodigoSeguimiento,omitempty"`
}

func (x *CodSeguimiento) Reset() {
	*x = CodSeguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodSeguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodSeguimiento) ProtoMessage() {}

func (x *CodSeguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodSeguimiento.ProtoReflect.Descriptor instead.
func (*CodSeguimiento) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{4}
}

func (x *CodSeguimiento) GetCodigoSeguimiento() int32 {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{5}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Orden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo    string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre  string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor   int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen  string `protobuf:"bytes,5,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Orden) Reset() {
	*x = Orden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orden) ProtoMessage() {}

func (x *Orden) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orden.ProtoReflect.Descriptor instead.
func (*Orden) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{6}
}

func (x *Orden) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Orden) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Orden) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Orden) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Orden) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Orden) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type DisponibleCamion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo           string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	EntrPrevRetail bool   `protobuf:"varint,3,opt,name=entrPrevRetail,proto3" json:"entrPrevRetail,omitempty"`
	PaqCargRetail  bool   `protobuf:"varint,4,opt,name=paqCargRetail,proto3" json:"paqCargRetail,omitempty"`
}

func (x *DisponibleCamion) Reset() {
	*x = DisponibleCamion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviciomensajeria_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisponibleCamion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisponibleCamion) ProtoMessage() {}

func (x *DisponibleCamion) ProtoReflect() protoreflect.Message {
	mi := &file_serviciomensajeria_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisponibleCamion.ProtoReflect.Descriptor instead.
func (*DisponibleCamion) Descriptor() ([]byte, []int) {
	return file_serviciomensajeria_proto_rawDescGZIP(), []int{7}
}

func (x *DisponibleCamion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DisponibleCamion) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *DisponibleCamion) GetEntrPrevRetail() bool {
	if x != nil {
		return x.EntrPrevRetail
	}
	return false
}

func (x *DisponibleCamion) GetPaqCargRetail() bool {
	if x != nil {
		return x.PaqCargRetail
	}
	return false
}

var File_serviciomensajeria_proto protoreflect.FileDescriptor

var file_serviciomensajeria_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a,
	0x65, 0x72, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x73, 0x6d, 0x22, 0x1d,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xef, 0x01,
	0x0a, 0x07, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x64,
	0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22,
	0x3a, 0x0a, 0x0f, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x6d, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x52, 0x08, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x22, 0x5a, 0x0a, 0x12, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x43, 0x6f,
	0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x3e, 0x0a, 0x0e, 0x43, 0x6f, 0x64, 0x53, 0x65,
	0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x64,
	0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x05, 0x4f, 0x72,
	0x64, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x70,
	0x6f, 0x6e, 0x69, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6e, 0x74, 0x72, 0x50, 0x72, 0x65, 0x76, 0x52, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x65, 0x6e, 0x74, 0x72, 0x50, 0x72,
	0x65, 0x76, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x61, 0x71, 0x43,
	0x61, 0x72, 0x67, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x70, 0x61, 0x71, 0x43, 0x61, 0x72, 0x67, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x32, 0xa9,
	0x02, 0x0a, 0x11, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x69, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x50,
	0x6f, 0x73, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x73, 0x6d, 0x2e, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x1a,
	0x0b, 0x2e, 0x73, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x0e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61,
	0x12, 0x13, 0x2e, 0x73, 0x6d, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x50, 0x61, 0x71,
	0x75, 0x65, 0x74, 0x65, 0x73, 0x1a, 0x0b, 0x2e, 0x73, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x69, 0x62, 0x65, 0x49, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x73, 0x6d,
	0x2e, 0x44, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x6d, 0x69, 0x6f,
	0x6e, 0x1a, 0x0b, 0x2e, 0x73, 0x6d, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x6e,
	0x12, 0x09, 0x2e, 0x73, 0x6d, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x1a, 0x12, 0x2e, 0x73, 0x6d,
	0x2e, 0x43, 0x6f, 0x64, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22,
	0x00, 0x12, 0x37, 0x0a, 0x13, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x53, 0x65, 0x67,
	0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x12, 0x2e, 0x73, 0x6d, 0x2e, 0x43, 0x6f,
	0x64, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x1a, 0x0a, 0x2e, 0x73,
	0x6d, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x67, 0x65, 0x6e, 0x3b, 0x73, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serviciomensajeria_proto_rawDescOnce sync.Once
	file_serviciomensajeria_proto_rawDescData = file_serviciomensajeria_proto_rawDesc
)

func file_serviciomensajeria_proto_rawDescGZIP() []byte {
	file_serviciomensajeria_proto_rawDescOnce.Do(func() {
		file_serviciomensajeria_proto_rawDescData = protoimpl.X.CompressGZIP(file_serviciomensajeria_proto_rawDescData)
	})
	return file_serviciomensajeria_proto_rawDescData
}

var file_serviciomensajeria_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_serviciomensajeria_proto_goTypes = []interface{}{
	(*Message)(nil),            // 0: sm.Message
	(*Paquete)(nil),            // 1: sm.Paquete
	(*InformePaquetes)(nil),    // 2: sm.InformePaquetes
	(*InformacionPaquete)(nil), // 3: sm.InformacionPaquete
	(*CodSeguimiento)(nil),     // 4: sm.CodSeguimiento
	(*Estado)(nil),             // 5: sm.Estado
	(*Orden)(nil),              // 6: sm.Orden
	(*DisponibleCamion)(nil),   // 7: sm.DisponibleCamion
}
var file_serviciomensajeria_proto_depIdxs = []int32{
	1, // 0: sm.InformePaquetes.paquetes:type_name -> sm.Paquete
	3, // 1: sm.MensajeriaService.EntregaPosicion:input_type -> sm.InformacionPaquete
	2, // 2: sm.MensajeriaService.InformaEntrega:input_type -> sm.InformePaquetes
	7, // 3: sm.MensajeriaService.RecibeInstrucciones:input_type -> sm.DisponibleCamion
	6, // 4: sm.MensajeriaService.RealizaOrden:input_type -> sm.Orden
	4, // 5: sm.MensajeriaService.SolicitaSeguimiento:input_type -> sm.CodSeguimiento
	0, // 6: sm.MensajeriaService.EntregaPosicion:output_type -> sm.Message
	0, // 7: sm.MensajeriaService.InformaEntrega:output_type -> sm.Message
	1, // 8: sm.MensajeriaService.RecibeInstrucciones:output_type -> sm.Paquete
	4, // 9: sm.MensajeriaService.RealizaOrden:output_type -> sm.CodSeguimiento
	5, // 10: sm.MensajeriaService.SolicitaSeguimiento:output_type -> sm.Estado
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serviciomensajeria_proto_init() }
func file_serviciomensajeria_proto_init() {
	if File_serviciomensajeria_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serviciomensajeria_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciomensajeria_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciomensajeria_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformePaquetes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciomensajeria_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformacionPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciomensajeria_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodSeguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciomensajeria_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciomensajeria_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviciomensajeria_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisponibleCamion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serviciomensajeria_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviciomensajeria_proto_goTypes,
		DependencyIndexes: file_serviciomensajeria_proto_depIdxs,
		MessageInfos:      file_serviciomensajeria_proto_msgTypes,
	}.Build()
	File_serviciomensajeria_proto = out.File
	file_serviciomensajeria_proto_rawDesc = nil
	file_serviciomensajeria_proto_goTypes = nil
	file_serviciomensajeria_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MensajeriaServiceClient is the client API for MensajeriaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MensajeriaServiceClient interface {
	//Camion
	EntregaPosicion(ctx context.Context, in *InformacionPaquete, opts ...grpc.CallOption) (*Message, error)
	InformaEntrega(ctx context.Context, in *InformePaquetes, opts ...grpc.CallOption) (*Message, error)
	RecibeInstrucciones(ctx context.Context, in *DisponibleCamion, opts ...grpc.CallOption) (*Paquete, error)
	//Cliente
	RealizaOrden(ctx context.Context, in *Orden, opts ...grpc.CallOption) (*CodSeguimiento, error)
	SolicitaSeguimiento(ctx context.Context, in *CodSeguimiento, opts ...grpc.CallOption) (*Estado, error)
}

type mensajeriaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMensajeriaServiceClient(cc grpc.ClientConnInterface) MensajeriaServiceClient {
	return &mensajeriaServiceClient{cc}
}

func (c *mensajeriaServiceClient) EntregaPosicion(ctx context.Context, in *InformacionPaquete, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/sm.MensajeriaService/EntregaPosicion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mensajeriaServiceClient) InformaEntrega(ctx context.Context, in *InformePaquetes, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/sm.MensajeriaService/InformaEntrega", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mensajeriaServiceClient) RecibeInstrucciones(ctx context.Context, in *DisponibleCamion, opts ...grpc.CallOption) (*Paquete, error) {
	out := new(Paquete)
	err := c.cc.Invoke(ctx, "/sm.MensajeriaService/RecibeInstrucciones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mensajeriaServiceClient) RealizaOrden(ctx context.Context, in *Orden, opts ...grpc.CallOption) (*CodSeguimiento, error) {
	out := new(CodSeguimiento)
	err := c.cc.Invoke(ctx, "/sm.MensajeriaService/RealizaOrden", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mensajeriaServiceClient) SolicitaSeguimiento(ctx context.Context, in *CodSeguimiento, opts ...grpc.CallOption) (*Estado, error) {
	out := new(Estado)
	err := c.cc.Invoke(ctx, "/sm.MensajeriaService/SolicitaSeguimiento", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MensajeriaServiceServer is the server API for MensajeriaService service.
type MensajeriaServiceServer interface {
	//Camion
	EntregaPosicion(context.Context, *InformacionPaquete) (*Message, error)
	InformaEntrega(context.Context, *InformePaquetes) (*Message, error)
	RecibeInstrucciones(context.Context, *DisponibleCamion) (*Paquete, error)
	//Cliente
	RealizaOrden(context.Context, *Orden) (*CodSeguimiento, error)
	SolicitaSeguimiento(context.Context, *CodSeguimiento) (*Estado, error)
}

// UnimplementedMensajeriaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMensajeriaServiceServer struct {
}

func (*UnimplementedMensajeriaServiceServer) EntregaPosicion(context.Context, *InformacionPaquete) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntregaPosicion not implemented")
}
func (*UnimplementedMensajeriaServiceServer) InformaEntrega(context.Context, *InformePaquetes) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformaEntrega not implemented")
}
func (*UnimplementedMensajeriaServiceServer) RecibeInstrucciones(context.Context, *DisponibleCamion) (*Paquete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecibeInstrucciones not implemented")
}
func (*UnimplementedMensajeriaServiceServer) RealizaOrden(context.Context, *Orden) (*CodSeguimiento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RealizaOrden not implemented")
}
func (*UnimplementedMensajeriaServiceServer) SolicitaSeguimiento(context.Context, *CodSeguimiento) (*Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitaSeguimiento not implemented")
}

func RegisterMensajeriaServiceServer(s *grpc.Server, srv MensajeriaServiceServer) {
	s.RegisterService(&_MensajeriaService_serviceDesc, srv)
}

func _MensajeriaService_EntregaPosicion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformacionPaquete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MensajeriaServiceServer).EntregaPosicion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sm.MensajeriaService/EntregaPosicion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MensajeriaServiceServer).EntregaPosicion(ctx, req.(*InformacionPaquete))
	}
	return interceptor(ctx, in, info, handler)
}

func _MensajeriaService_InformaEntrega_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformePaquetes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MensajeriaServiceServer).InformaEntrega(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sm.MensajeriaService/InformaEntrega",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MensajeriaServiceServer).InformaEntrega(ctx, req.(*InformePaquetes))
	}
	return interceptor(ctx, in, info, handler)
}

func _MensajeriaService_RecibeInstrucciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisponibleCamion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MensajeriaServiceServer).RecibeInstrucciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sm.MensajeriaService/RecibeInstrucciones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MensajeriaServiceServer).RecibeInstrucciones(ctx, req.(*DisponibleCamion))
	}
	return interceptor(ctx, in, info, handler)
}

func _MensajeriaService_RealizaOrden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Orden)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MensajeriaServiceServer).RealizaOrden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sm.MensajeriaService/RealizaOrden",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MensajeriaServiceServer).RealizaOrden(ctx, req.(*Orden))
	}
	return interceptor(ctx, in, info, handler)
}

func _MensajeriaService_SolicitaSeguimiento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodSeguimiento)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MensajeriaServiceServer).SolicitaSeguimiento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sm.MensajeriaService/SolicitaSeguimiento",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MensajeriaServiceServer).SolicitaSeguimiento(ctx, req.(*CodSeguimiento))
	}
	return interceptor(ctx, in, info, handler)
}

var _MensajeriaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sm.MensajeriaService",
	HandlerType: (*MensajeriaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntregaPosicion",
			Handler:    _MensajeriaService_EntregaPosicion_Handler,
		},
		{
			MethodName: "InformaEntrega",
			Handler:    _MensajeriaService_InformaEntrega_Handler,
		},
		{
			MethodName: "RecibeInstrucciones",
			Handler:    _MensajeriaService_RecibeInstrucciones_Handler,
		},
		{
			MethodName: "RealizaOrden",
			Handler:    _MensajeriaService_RealizaOrden_Handler,
		},
		{
			MethodName: "SolicitaSeguimiento",
			Handler:    _MensajeriaService_SolicitaSeguimiento_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviciomensajeria.proto",
}
